# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

logging:
  level:
    ROOT: INFO
    com.personal.taskmanagement: INFO

spring:
  config:
    active:
      on-profile: "prod"

server:
  port: 8082
