# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

#logging:
#  level:
#    ROOT: DEBUG
#    com.personal.taskmanagement: DEBUG

spring:
  config:
    active:
      on-profile: "dev"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true

server:
  port: 8080

application:
  # CORS is only enabled by default with the "dev" profile
  cors:
    allowed-origins: "*"
    allowed-methods: "GET, HEAD, POST, PUT, DELETE"
    allowed-headers: "*"
    max-age: 1800

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
