on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for Secrets
        uses: gitleaks/gitleaks-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - run: chmod +x ./gradlew
      - name: Check Java Style (Checkstyle)
        run: ./gradlew checkstyleMain checkstyleTest
      - run: ./gradlew build